### ISSUE TITLE
yafaray interface_t

### ISSUE THREAD

**Issue by hergljkds** [YafaRay/libYafaRay-Xml#1]
This package does not build as is... interface_t is not appropriately defined.

**Comment by DavidBluecame** [comment]
Hello,

My apologies, currently I'm in the middle of a huge refactoring of the YafaRay codebase and API for the upcoming v4 and currently the XML and Python projects are lagging behind the latest libYafaRay API changes.

I hope to work on YafaRay and these other surrounding projects over the next few weeks so I can get all into a consistent state. I'll leave this ticket open until all this is corrected.

Thanks for your patience and best regards.

**Comment by hergljkds** [comment]
Is a header missing?  ...the def does not appear to be present.

**Comment by hergljkds** [comment]
Is there a libyafaray commit that is compatible with master head yafaray-xml?

**Comment by DavidBluecame** [comment]
Yes, the current libYafaRay-Xml should be compatible with this libYafaRay commit:
https://github.com/YafaRay/libYafaRay/commit/0c3094781df5caa940c35837e1f10342666f0c1f

However I still expect to make quite a few changes to both, including the XML format itself.

**Comment by DavidBluecame** [comment]
Hello, I've made updates to libYafaRay-Xml to update it to work with the latest libYafaRay API.

Keep in mind that at the moment all libYafaRay v4.0.0 code is unstable/pre-alpha, so the API might change anytime in unexpected ways. I'm also heavily modifying the XML format itself, so it will not be compatible with v3.5.1 nor with previous v4.0.0 pre-alpha code.

**Comment by DavidBluecame** [comment]
Hello, @hergljkds 

Thank you for the information. Is that error happening when building in Linux or Windows? If in Windows I will need some time to set up the necessary dependencies to try building it to check.

What is the include that is needed?

About the test xml file there is one in the tests folder in the code. That is the one I use for basic testing, with the intended XML structure.

**Comment by hergljkds** [comment]
odd... the header should have been included above (ha)

system include, in file command_line_parser.h:

#include <memory>

...insight into the problem.

**Comment by hergljkds** [comment]
odd... the header should have been included above (ha)

system include, in file command_line_parser.h:

#include \<memory\>

...insight into the problem.

**Comment by DavidBluecame** [comment]
Thank you for the information, I've added the missing header.
